POST http://localhost:9011/SV4/BillsTable/Insert/SchemaColumnsOnly
Content-Type: application/json

{
  "BuyerName": "",
  "BuyerAddress": "",
  "BuyerGST": "",
  "InvoiceNo": "",
  "InvoiceDate": "",
  "InvoiceStateCode": ""
}
